baseURL = "https://svenshen.com"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Call Me Sven"
    signature = "人生如逆旅，我亦是行人。"
    cover = "/img/cover.jpg"

    name = "Sven"
    avatar = "/img/sven_avatar.jpeg"
